# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "manual"
    # Create a group of dependencies to be updated together in one pull request
    groups:
      BenchmarkDotNet:
        patterns:
          - "BenchmarkDotNet*"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "manual"
    open-pull-requests-limit: 20
